version: "3.1"

services:
        wordpress:
                image: wordpress:4.9.4-php7.2-fpm
                restart: always
                depends_on:
                        - database
                volumes:
                        - ./var/www/html:/var/www/html
                environment:
                        WORDPRESS_DB_HOST: database:3306
                        WORDPRESS_DB_USER: fixme
                        WORDPRESS_DB_PASSWORD: fixme
                        WORDPRESS_DB_NAME: fixme
        webserver:
                 image: nginx:1.13.9
                 restart: always
                 ports:
                         - 80:80
                 volumes:
                         - ./var/www/html:/var/www/html
                         - ./docker/nginx/wordpress.conf:/etc/nginx/conf.d/default.conf
                 depends_on:
                         - wordpress
        database:
                image: mariadb:10.3.5
                restart: always
                environment:
                        MYSQL_DATABASE: fixme
                        MYSQL_ROOT_PASSWORD: fixme
                        MYSQL_USER: fixme
                        MYSQL_PASSWORD: fixme

        # add varnish
        # add https support
        # add redis
